version: '2'

networks:
  mongodb-tier:
    driver: bridge
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - ./mongodb:/bitnami/mongodb
    networks:
      - mongodb-tier